export { AddressStepPage } from "./address-step.page"
export { MenuContentPage } from "./menu-content.page"
export { ProductsListPage } from "./products-list.page"
export { LoginPage } from "./login.page"
export { ShippingStepPage } from "./shipping-step.page"
export { PaymentStepPage } from "./payment-step.page"
export { DressesListPage} from "./dresses-list.page"
export { ShoppingCartPage} from "./shopping-cart.page"
export { PersonalFormPage} from "./personal-form.page"
export {UploadPage} from "./upload.page"
